CREATE DATABASE IF NOT EXISTS VENDA;
USE VENDA;

CREATE TABLE  IF NOT EXISTS  CIDADE 
(
   IDCIDADE INT NOT NULL PRIMARY KEY,
   NOMECIDADE VARCHAR(50),
   SIGLAESTADO VARCHAR(2)
);

CREATE TABLE  IF NOT EXISTS  CLIENTE 
(
    IDCLIENTE INT NOT NULL PRIMARY KEY,
    NOMECLIENTE VARCHAR(50),
    ENDERCLIENTE VARCHAR(50),
    CPFCLIENTE VARCHAR(20),
    FONECLIENTE VARCHAR(20),
    IDCIDADE INT,
    FOREIGN KEY(IDCIDADE) REFERENCES CIDADE(IDCIDADE)
);

CREATE TABLE  IF NOT EXISTS  VENDA
(
    IDVENDA INT NOT NULL PRIMARY KEY,
    DATAVENDA DATE,
    HORAVENDA TIME,
    VALORVENDA NUMERIC(8,2),
    IDCLIENTE INT,
    FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE  IF NOT EXISTS  PRODUTO
(
    IDPRODUTO INT NOT NULL PRIMARY KEY,
    DESCRPRODUTO VARCHAR(50),
    VALORPRODUTO NUMERIC(8,2),
    QTDEPRODUTO INT
);

CREATE TABLE  IF NOT EXISTS  ITENSVENDA
(
    IDVENDA INT NOT NULL,
    IDPRODUTO INT NOT NULL,
    IDITENS INT NOT NULL,
    QTDEITENS INT,
    VALORITENS NUMERIC(8,2),
    PRIMARY KEY(IDVENDA,IDPRODUTO,IDITENS),
    FOREIGN KEY(IDVENDA) REFERENCES VENDA(IDVENDA),
    FOREIGN KEY(IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

CREATE TABLE IF NOT EXISTS Atributos
(
	ID	INT NOT NULL PRIMARY KEY,
    ELEMENTO	VARCHAR(10) NOT NULL,
    RARIDADE	VARCHAR(1) NOT NULL,
    ARMA		VARCHAR(20) NOT NULL,
    MODELO		VARCHAR(15),
    GENERO		VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS Personagens
(
	IDPERSO		INT NOT NULL PRIMARY KEY,
    NOMEPERSO	VARCHAR(50) NOT NULL,
    AtributoId 	INT NOT NULL,
	FOREIGN KEY(AtributoId) REFERENCES Atributos(ID)
);

INSERT INTO ATRIBUTOS(ELEMENTO) VALUES 
('Pyro'), ('Cryo'), ('Anemo')



